# Change these first
owner: travnettech # Your GitHub organization or username, where this repository lives
repo: ncl_status # The name of this repository

sites:
  - name: Website
    url: https://nelsoncollege.ac.uk
    icon: https://portal.nelsoncollege.ac.uk/files/logo-main.svg
  - name: Virtual Learning Environment VLE
    url: https://nclvle.co.uk
    icon: https://portal-nelsoncollege-files.s3.eu-west-2.amazonaws.com/logo/VLE_NCL.svg
  - name: Nelson One
    url: https://one.nelsoncollege.ac.uk
    icon: https://portal-nelsoncollege-files.s3.eu-west-2.amazonaws.com/logo/One_NCL.svg
  - name: Nelson Portal
    url: https://portal.nelsoncollege.ac.uk
    icon: https://portal.nelsoncollege.ac.uk/files/logo-main.svg
  - name: Knowledge Exchange Centre
    url: https://kec.nelsoncollege.ac.uk
    icon: https://portal-nelsoncollege-files.s3.eu-west-2.amazonaws.com/logo/KEC_NCL.svg
  - name: NCL Alumni Association
    url: https://alumni.nelsoncollege.ac.uk
    icon: https://portal-nelsoncollege-files.s3.eu-west-2.amazonaws.com/logo/Alumni_NCL.svg

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.nelsoncollege.ac.uk
  # baseUrl: /your-repo-name
  logoUrl: https://portal.nelsoncollege.ac.uk/files/logo-main.svg
  name: Nelson Status
  introTitle: "**Welcome to Nelson Status page.**"
  introMessage: From here you will be able find real-time information about the status of our environments as well as updates about scheduled maintenance and past incidents. To better understand the content of this page, and which areas pertain to you, please contact [**it@nelsoncollege.ac.uk**](mailto:it@nelsoncollege.ac.uk).
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://nelsoncollege.ac.uk

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
